version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: nuget
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday